FROM node:lts-alpine as build-stage
COPY ./new.conf /etc/nginx/conf.d/default.conf
WORKDIR /app
COPY frontend/package*.json ./
RUN npm install
COPY ./frontend/ .
RUN npm run build

# production stage
FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 8000
CMD ["nginx", "-g", "daemon off;"]
