FROM python:3.7
WORKDIR /code
ENV PYTHONUNBUFFERED=1
COPY wait.sh /wait.sh
RUN chmod +x /wait.sh
COPY requirements.txt /tmp/
RUN pip install -r /tmp/requirements.txt
ADD ./ /code
CMD /wait.sh db 5432 \
  && python mysite/manage.py collectstatic --noinput \
  && python mysite/manage.py migrate \
  && python mysite/manage.py loaddata data.json \
  && /usr/local/bin/uwsgi --ini /code/mysite/mysite/uwsgi.ini